# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-07 20:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='show',
        ),
        migrations.RemoveField(
            model_name='post',
            name='show',
        ),
    ]
